name: MinecraftCommands
version: '1.0.1'
main: me.touchie771.minecraftCommands.MinecraftCommands
api-version: '1.21'
authors: [ Touchie771 ]
description: A library made for shortening command handling.